name: Initial Full Deployment

on:
  workflow_dispatch:  # Manual trigger for first deployment

jobs:
  deploy-all:
    uses: ./.github/workflows/full-deployment.yml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
